### ISSUE TITLE
Private sub-module causing unit-tests to fail

### ISSUE THREAD

**Issue by mcsloy** [tbmalt/tbmalt#7]
Unit tests are failing due to a permissions error associated with the "`external`" sub-module. This model points to the following GitHub repository `https://github.com/grimme-lab/dxtb/tree/46d64d40f9e33ae4e72bc932b6111a2f30b6d783`. This repository is private and thus cannot be accessed. This results in an error when running the unit-test file `test_xtb.py` as it attempts to import `GFN1_XTB` and `get_elem_angular` from `external.dxtb.origin.dxtb.param`. Once we fix this the unit-tests should stop screaming at us. I would tentatively suggest making this repository public.

**Comment by marvinfriede** [comment]
Yes, I know. I already talked to @aradi about this. Unfortunately, @hoelzerC and I are not ready to fully release `dxtb` yet. Until then, I removed the corresponding tests and added some exceptions (#6).
The unit tests are now working, the error for Python 3.9 is thrown by the last test in `test_mixers.py`.

**Comment by mcsloy** [comment]
Thank you, that makes sense. I am still working my way though the pull requests.
